apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: "DevilCOM Local CA"
  secretName: local-ca-key-pair
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: local-ca
spec:
  ca:
    secretName: local-ca-key-pair
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: media-lan-tls
  namespace: infra
  annotations:
    reflector.emberstack.com/reflection-allowed: "true"
    reflector.emberstack.com/reflection-allowed-namespaces: "ingress-traefik-infra,ingress-traefik-media"
    reflector.emberstack.com/reflection-auto: "true"
    reflector.emberstack.com/reflection-auto-namespaces: "ingress-traefik-infra,ingress-traefik-media"
spec:
  secretName: media-lan-tls
  duration: 2160h
  renewBefore: 360h
  commonName: "*.lan"
  subject:
    organizations:
      - "DevilCOM Network"
    organizationalUnits:
      - "Media Cluster"
  isCA: false
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "infra.lan"
    - "media.lan"
    - "*.infra.lan"
    - "*.media.lan"
  issuerRef:
    name: local-ca
    kind: ClusterIssuer
    group: cert-manager.io
