apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dynu
spec:
  acme:
    email: ${ACME_EMAIL}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dynu-account-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.dynu.com
            solverName: dynu
            config:
              secretName: dynu-api-key-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wan-wildcard-tls
  namespace: infra
spec:
  secretName: wan-wildcard-tls
  secretTemplate:
    annotations:
      reflector.emberstack.com/reflection-allowed: "true"
      reflector.emberstack.com/reflection-allowed-namespaces: "media"
      reflector.emberstack.com/reflection-auto: "true"
      reflector.emberstack.com/reflection-auto-namespaces: "media"
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt-dynu
    kind: ClusterIssuer
  commonName: "${WAN_HOSTNAME}"
  dnsNames:
    - "${WAN_HOSTNAME}"
    - "*.${WAN_HOSTNAME}"
    - "*.infra.${WAN_HOSTNAME}"
    - "*.media.${WAN_HOSTNAME}"
    - "*.cloud.${WAN_HOSTNAME}"
  usages:
    - digital signature
    - key encipherment
    - server auth
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        key: password
        name: wan-cert-password
---
apiVersion: v1
kind: Secret
metadata:
  name: wan-cert-password
  namespace: infra
type: Opaque
stringData:
  password: "${WAN_CERT_KEYSTORE_PASSWORD}"
