apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gzip
  namespace: ingress-traefik-infra
spec:
  compress:
    includedContentTypes:
      - "text/html"
      - "text/css"
      - "text/plain"
      - "text/javascript"
      - "text/xml"
      - "application/json"
      - "application/javascript"
      - "application/xml"
      - "application/xhtml+xml"
      - "application/rss+xml"
      - "application/atom+xml"
      - "image/svg+xml"
    minResponseBodyBytes: 1024
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: error-pages
  namespace: ingress-traefik-infra
spec:
  errors:
    status:
      - "502-504"
    query: "/{status}.html"
    service:
      name: custom-error-pages
      namespace: infra
      port: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: error-pages-aggressive
  namespace: ingress-traefik-infra
spec:
  errors:
    status:
      - "400"
      - "402-599"
    query: "/{status}.html"
    service:
      name: custom-error-pages
      namespace: infra
      port: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: infra
spec:
  redirectScheme:
    scheme: https
    permanent: true
