user              nginx;
worker_processes  auto;
error_log         /var/log/nginx/error.log warn;
pid               /var/run/nginx.pid;

events {
	worker_connections 1024;
}

http {
	include            /etc/nginx/mime.types;
	default_type       application/octet-stream;
	sendfile           on;
	keepalive_timeout  65;

	upstream plex {
		server plex:32400;
	}
	upstream emby {
		server emby:8096;
	}
	upstream sonarr {
		server sonarr:8989;
	}
	upstream radarr {
		server radarr:7878;
	}
	upstream prowlarr {
		server prowlarr:9696;
	}
	upstream profilarr {
		server profilarr:6868;
	}
	upstream jackett {
		server jackett:9117;
	}

	server {
		listen 80;
		server_name localhost;

		location ~ ^/(|emby)$ {
			return 301 http://emby.local;
		}
		location /plex {
			return 301 http://plex.local;
		}
		location /sonarr {
			return 301 http://sonarr.local;
		}
		location /radarr {
			return 301 http://radarr.local;
		}
		location /prowlarr {
			return 301 http://prowlarr.local;
		}
		location /profilarr {
			return 301 http://profilarr.local;
		}
		location /jackett {
			return 301 http://jackett.local;
		}
	}

	server {
		listen 80;
		server_name plex.local;
		location / {
			proxy_pass http://plex;
      include /etc/nginx/proxy_common.conf;
		}
	}

	server {
		listen 80;
		server_name emby.local;
		location / {
			proxy_pass http://emby;
      include /etc/nginx/proxy_common.conf;
		}
	}

	server {
		listen 80;
		server_name sonarr.local;
		location / {
			proxy_pass http://sonarr;
			include /etc/nginx/proxy_common.conf;
		}
	}

	server {
		listen 80;
		server_name radarr.local;
		location / {
			proxy_pass http://radarr;
      include /etc/nginx/proxy_common.conf;
		}
	}

	server {
		listen 80;
		server_name prowlarr.local;
		location / {
			proxy_pass http://prowlarr;
      include /etc/nginx/proxy_common.conf;
		}
	}

	server {
		listen 80;
		server_name profilarr.local;
		location / {
			proxy_pass http://profilarr;
      include /etc/nginx/proxy_common.conf;
		}
	}

  server {
    listen 80;
    server_name jackett.local;
    location / {
      proxy_pass http://jackett;
      include /etc/nginx/proxy_common.conf;
    }
  }
}
