user              nginx;
worker_processes  auto;
error_log         /var/log/nginx/error.log warn;
pid               /var/run/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include            /etc/nginx/mime.types;
  default_type       application/octet-stream;
  sendfile           on;
  keepalive_timeout  65;

  upstream plex {
    server plex:32400;
  }
  upstream emby {
    server emby:8096;
  }
  upstream sonarr {
    server sonarr:8989;
  }
  upstream sonarr_https {
    server sonarr:9898;
  }
  upstream radarr {
    server radarr:7878;
  }
  upstream radarr_https {
    server radarr:8787;
  }
  upstream prowlarr {
    server prowlarr:9696;
  }
  upstream prowlarr_https {
    server prowlarr:6969;
  }
  upstream profilarr {
    server profilarr:6868;
  }
  upstream jackett {
    server jackett:9117;
  }

  server {
    listen 80;
    server_name plex.local;
    location / {
      proxy_pass http://plex;
      include /etc/nginx/proxy_common.conf;
    }
  }

  server {
    listen 80;
    server_name emby.local;
    location / {
      proxy_pass http://emby;
      include /etc/nginx/proxy_common.conf;
    }
  }

  # Emby local HTTPS server block
  server {
    listen 443 ssl;
    server_name emby.local;
    ssl_certificate /config/emby.local.crt;
    ssl_certificate_key /config/emby.local.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    location / {
      proxy_pass http://emby;
      include /etc/nginx/proxy_common.conf;
    }
  }

  server {
    listen 80;
    server_name sonarr.local;
    location / {
      proxy_pass http://sonarr;
        include /etc/nginx/proxy_common.conf;
    }
  }

  server {
    listen 443 ssl;
    server_name sonarr.local;
    ssl_certificate /config/sonarr.local.crt;
    ssl_certificate_key /config/sonarr.local.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    location / {
      proxy_pass https://sonarr_https;
      include /etc/nginx/proxy_common.conf;
    }
  }

  server {
    listen 80;
    server_name radarr.local;
    location / {
      proxy_pass http://radarr;
      include /etc/nginx/proxy_common.conf;
    }
  }

  server {
    listen 443 ssl;
    server_name radarr.local;
    ssl_certificate /config/radarr.local.crt;
    ssl_certificate_key /config/radarr.local.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    location / {
      proxy_pass https://radarr_https;
      include /etc/nginx/proxy_common.conf;
    }
  }

  server {
    listen 80;
    server_name prowlarr.local;
    location / {
      proxy_pass http://prowlarr;
      include /etc/nginx/proxy_common.conf;
    }
  }

  server {
    listen 443 ssl;
    server_name prowlarr.local;
    ssl_certificate /config/prowlarr.local.crt;
    ssl_certificate_key /config/prowlarr.local.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    location / {
      proxy_pass https://prowlarr_https;
      include /etc/nginx/proxy_common.conf;
    }
  }

  server {
    listen 80;
    server_name profilarr.local;
    location / {
      proxy_pass http://profilarr;
      include /etc/nginx/proxy_common.conf;
    }
  }

  server {
    listen 80;
    server_name jackett.local;
    location / {
      proxy_pass http://jackett;
      include /etc/nginx/proxy_common.conf;
    }
  }
}
