#!/bin/bash
set -e

build_and_load_image "$SONARR_IMAGE_NAME" "$SONARR_DOCKERFILE_PATH" "$DOCKER_BUILD_CONTEXT" "$CLUSTER_NAME"
build_and_load_image "$RADARR_IMAGE_NAME" "$RADARR_DOCKERFILE_PATH" "$DOCKER_BUILD_CONTEXT" "$CLUSTER_NAME"
