apiVersion: v1
kind: ConfigMap
metadata:
   name: coredns
   namespace: kube-system
data:
   Corefile: |
      .:53 {
          errors
          health {
             lameduck 5s
          }
          ready

          kubernetes cluster.local in-addr.arpa ip6.arpa {
             pods insecure
             fallthrough in-addr.arpa ip6.arpa
             ttl 30
          }
          prometheus :9153

          # Encaminhamento para BIND local (uso de IP estático 10.96.0.53 para evitar erro de inicialização do plugin forward)
          forward lan 10.96.0.53
          forward ${WAN_HOSTNAME} 10.96.0.53

          # DNS Upstream Padrão: usa o resolver do Docker (Kind)
          forward . 0.250.250.254 {
             except cluster.local lan ${WAN_HOSTNAME}
          }

          cache 30
          loop
          reload
          loadbalance
      }
