apiVersion: v1
kind: ConfigMap
metadata:
   name: coredns
   namespace: kube-system
data:
   Corefile: |
      .:53 {
          errors
          health {
             lameduck 5s
          }
          ready

          kubernetes cluster.local in-addr.arpa ip6.arpa {
             pods insecure
             fallthrough in-addr.arpa ip6.arpa
             ttl 30
          }
          prometheus :9153

          # Encaminhamento para BIND no cluster Infra (NodePort)
          forward media.lan 192.168.97.2:30053
          forward infra.lan 192.168.97.2:30053
          forward ${WAN_HOSTNAME} 192.168.97.2:30053

          # Descoberta Nativa: pergunta ao DNS interno do Docker (Kind)
          forward . 0.250.250.254 {
             except cluster.local media.lan infra.lan ${WAN_HOSTNAME}
          }

          cache 30
          loop
          reload
          loadbalance
      }
