apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready

        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153

        # Descoberta Nativa: pergunta ao DNS interno do Docker (Kind)
        # 0.250.250.254 é o resolver padrão do Docker para responder sobre containers
        forward . 0.250.250.254 {
           except cluster.local
        }

        cache 30
        loop
        reload
        loadbalance
    }
