apiVersion: batch/v1
kind: CronJob
metadata:
  name: wan-cert-backup
  namespace: infra
spec:
  schedule: "0 0 * * *" # Run daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: bitnami/kubectl:latest
              command:
                - /bin/bash
                - /mnt/scripts/k8s/backup-wan-cert.sh
              volumeMounts:
                - name: configs
                  subPath: backups
                  mountPath: /mnt/backups
                - name: scripts
                  mountPath: /mnt/scripts
          restartPolicy: OnFailure
          serviceAccountName: wan-cert-backup
          volumes:
            - name: configs
              persistentVolumeClaim:
                claimName: configs-pvc
            - name: scripts
              persistentVolumeClaim:
                claimName: scripts-pvc
