apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      priorityClassName: critical-media
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
      - name: plex
        image: plexinc/pms-docker:latest
        ports:
        - containerPort: 32400
          name: pms
        - name: gdm-32410
          containerPort: 32410
          protocol: UDP
        - name: gdm-32412
          containerPort: 32412
          protocol: UDP
        - name: gdm-32413
          containerPort: 32413
          protocol: UDP
        - name: gdm-32414
          containerPort: 32414
          protocol: UDP
        - name: companion
          containerPort: 8324
        livenessProbe:
          tcpSocket:
            port: 32400
          initialDelaySeconds: 30
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 32400
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Sao_Paulo"
        - name: ADVERTISE_IP
          value: "${PLEX_ADVERTISE_IP}"
        - name: PLEX_CLAIM
          value: "${PLEX_CLAIM}"
        - name: VERSION
          value: "docker"
        volumeMounts:
        - name: configs-source
          mountPath: /config
          subPath: plex
        - name: media
          mountPath: /media
        - name: transcode
          mountPath: /transcode
      volumes:
      - name: configs-source
        persistentVolumeClaim:
          claimName: configs-pvc
      - name: media
        persistentVolumeClaim:
          claimName: media-pvc
      - name: transcode
        emptyDir:
          medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
spec:
  selector:
    app: plex
  type: ClusterIP
  ports:
    - name: pms
      port: 32400
      targetPort: 32400
      protocol: TCP
    - name: gdm-32410
      port: 32410
      targetPort: 32410
      protocol: UDP
    - name: gdm-32412
      port: 32412
      targetPort: 32412
      protocol: UDP
    - name: gdm-32413
      port: 32413
      targetPort: 32413
      protocol: UDP
    - name: gdm-32414
      port: 32414
      targetPort: 32414
      protocol: UDP
    - name: companion
      port: 8324
      targetPort: 8324
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-ingress
  namespace: media
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - "plex.media.lan"
    secretName: media-lan-tls
  - hosts:
    - "plex.apedamo.duckdns.org"
    secretName: media-wan-tls
  rules:
  - host: "plex.media.lan"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plex
            port:
              number: 32400
  - host: "plex.apedamo.duckdns.org"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plex
            port:
              number: 32400
