apiVersion: apps/v1
kind: Deployment
metadata:
  name: profilarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profilarr
  template:
    metadata:
      labels:
        app: profilarr
    spec:
      containers:
      - name: profilarr
        image: santiagosayshey/profilarr:latest
        ports:
        - containerPort: 6868
        livenessProbe:
          tcpSocket:
            port: 6868
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 6868
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Sao_Paulo"
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 64Mi
        volumeMounts:
        - name: configs-source
          mountPath: /config
          subPath: profilarr
      volumes:
      - name: configs-source
        persistentVolumeClaim:
          claimName: configs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: profilarr
  namespace: media
spec:
  selector:
    app: profilarr
  ports:
    - port: 6868
      targetPort: 6868
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: profilarr-ingress
  namespace: media
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "profilarr.media.lan"
    secretName: media-lan-tls
  rules:
  - host: "profilarr.media.lan"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: profilarr
            port:
              number: 6868
