apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: ${RADARR_IMAGE_NAME}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7878
          name: radarr
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: 7878
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 7878
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Sao_Paulo"
        volumeMounts:
        - name: configs
          mountPath: /config
          subPath: radarr
        - name: downloads
          mountPath: /downloads
        - name: media
          mountPath: /media
        - name: scripts
          mountPath: /opt/scripts
          subPath: arr
          readOnly: true
      volumes:
      - name: configs
        persistentVolumeClaim:
          claimName: configs-pvc
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads-pvc
      - name: media
        persistentVolumeClaim:
          claimName: media-pvc
      - name: scripts
        persistentVolumeClaim:
          claimName: scripts-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media
spec:
  selector:
    app: radarr
  ports:
    - port: 7878
      targetPort: 7878
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr-lan
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`radarr.media.lan`)
      kind: Rule
      services:
        - name: radarr
          port: 7878
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr-lan-http
  namespace: media
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`radarr.media.lan`)
      kind: Rule
      middlewares:
        - name: https-redirect
          namespace: media
      services:
        - name: radarr
          port: 7878
