apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: media
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
  - apiGroups: ["traefik.io", "traefik.containo.us"]
    resources: ["ingressroutes", "ingressroutetcps", "ingressrouteudps"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods", "nodes"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: media
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: media
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.15.1
          args:
            - --source=traefik-proxy
            - --traefik-disable-legacy
            - --domain-filter=media.lan.
            - --domain-filter=media.${WAN_HOSTNAME}.
            - --domain-filter=infra.lan.
            - --domain-filter=infra.${WAN_HOSTNAME}.
            - --provider=rfc2136
            - --rfc2136-host=homelab-cluster-control-plane
            - --rfc2136-port=30053
            - --rfc2136-zone=media.lan
            - --rfc2136-zone=media.${WAN_HOSTNAME}
            - --rfc2136-tsig-secret-alg=hmac-sha256
            - --rfc2136-tsig-keyname=externaldns-key
            - --rfc2136-min-ttl=60s
            - --log-level=debug
          env:
            - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
              valueFrom:
                secretKeyRef:
                  name: rfc2136-tsig-secret
                  key: tsig-secret
