apiVersion: v1
kind: ConfigMap
metadata:
   name: coredns
   namespace: kube-system
   annotations:
      kubectl.kubernetes.io/last-applied-configuration: ""
data:
   Corefile: |
      .:53 {
          errors
          health {
             lameduck 5s
          }
          ready

          kubernetes cluster.local in-addr.arpa ip6.arpa {
             pods insecure
             fallthrough in-addr.arpa ip6.arpa
             ttl 30
          }
          prometheus :9153

          # Encaminhamento para BIND local (uso de IP estático 192.168.194.239)
          forward lan 192.168.194.239
          forward ${WAN_HOSTNAME} 192.168.194.239

          # DNS Upstream Padrão: usa Resolvers Públicos no OrbStack
          forward . 8.8.8.8 1.1.1.1 {
             except cluster.local lan ${WAN_HOSTNAME}
          }

          cache 30
          loop
          reload
          loadbalance
      }
