name: media

services:
  # Public Media Services
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    hostname: plex
    volumes:
      - ${CONFIGS_PATH:-.}/plex:/config
      - media_data:/media
    environment:
      ADVERTISE_IP: ${PLEX_ADVERTISE_IP:-}
      PGID: 1000
      PLEX_CLAIM: ${PLEX_CLAIM:-}
      PUID: 1000
      TZ: America/Sao_Paulo
      VERSION: docker
    ports:
      - 32400:32400/tcp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 8324:8324/tcp
    networks:
      - media-network
    restart: on-failure

  emby:
    image: emby/embyserver_arm64v8:latest
    container_name: emby
    hostname: emby
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Sao_Paulo
    volumes:
      - ${CONFIGS_PATH:-.}/emby:/config
      - media_data:/media
    ports:
      - 8096:8096
    networks:
      - media-network
    restart: on-failure

  # Private Media Services
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Sao_Paulo
    volumes:
      - ${CONFIGS_PATH:-.}/bazarr:/config
      - media_data:/media
    expose:
      - 6767
    networks:
      - media-network
      - proxy-network
    restart: on-failure

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    hostname: flaresolverr
    environment:
      CAPTCHA_SOLVER: none
      LOG_HTML: false
      LOG_LEVEL: info
      TZ: America/Sao_Paulo
    expose:
      - 8191
    networks:
      - media-network
    restart: on-failure

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    hostname: jackett
    environment:
      AUTO_UPDATE: true
      PGID: 1000
      PUID: 1000
      TZ: America/Sao_Paulo
    volumes:
      - ${CONFIGS_PATH:-.}/jackett:/config
      - downloads_data:/downloads
    expose:
      - 9117
    networks:
      - media-network
      - proxy-network
    restart: on-failure

  profilarr:
    image: santiagosayshey/profilarr:latest
    container_name: profilarr
    hostname: profilarr
    volumes:
      - ${CONFIGS_PATH:-.}/profilarr:/config
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Sao_Paulo
    expose:
      - 6868
    networks:
      - media-network
    restart: on-failure

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    volumes:
      - ${CONFIGS_PATH:-.}/prowlarr:/config
      - media_data:/media
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Sao_Paulo
    expose:
      - 9696
    networks:
      - media-network
      - proxy-network
    restart: on-failure

  radarr:
    image: radarr-mkvtoolnix
    container_name: radarr
    hostname: radarr
    volumes:
      - ${CONFIGS_PATH:-.}/radarr:/config
      - scripts_data:/opt/scripts
      - media_data:/media
      - downloads_data:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    expose:
      - 7878
    networks:
      - media-network
    restart: on-failure

  sonarr:
    image: sonarr-mkvtoolnix
    container_name: sonarr
    hostname: sonarr
    volumes:
      - ${CONFIGS_PATH:-.}/sonarr:/config
      - scripts_data:/opt/scripts
      - media_data:/media
      - downloads_data:/downloads
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Sao_Paulo
    expose:
      - 8989
    networks:
      - media-network
    restart: on-failure

  # Infrastructure Services
  caddy:
    image: caddy:latest
    container_name: caddy
    hostname: caddy
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # HTTP/3 (QUIC)
    volumes:
      - ${CONFIGS_PATH:-.}/caddy/data:/data
      - ${CONFIGS_PATH:-.}/caddy/config:/config
      - ${CONFIGS_PATH:-.}/caddy/Caddyfile:/etc/caddy/Caddyfile:rw
      - certs_lan_data:/certs/lan:ro
      - certs_wan_data:/certs/wan:ro
    networks:
      - media-network
      - infra-network
    restart: on-failure

  dns:
    image: coredns/coredns:latest
    container_name: dns
    hostname: dns
    environment:
      TZ: America/Sao_Paulo
      DOCKER_HOST_IP: ${DOCKER_HOST_IP:-}
      PUBLIC_DNS_IP: ${PUBLIC_DNS_IP:-}
    ports:
      - 53:53/udp
    volumes:
      - ${CONFIGS_PATH:-.}/coredns/Corefile:/Corefile
      - ${CONFIGS_PATH:-.}/coredns/configs:/etc/coredns/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - infra-network
      - media-network

  proxy:
    image: ghcr.io/tarampampam/3proxy
    container_name: proxy
    hostname: proxy
    volumes:
      - ${CONFIGS_PATH:-.}/3proxy/3proxy.cfg:/etc/3proxy/3proxy.cfg
    environment:
      EXTRA_CONFIG: |
        auth iponly
        allow * * *.media.lan * *
        allow * * *.plex.direct * *
        allow * * ${MEDIA_SUBNET_CIDR:-172.16.0.0/24} * *
        allow * * ${PROXY_SUBNET_CIDR:-172.16.1.0/24} * *
        parent 1000 connect+ 0.0.0.0 0
        allow *
        parent 1000 ${PROXY_TYPE} ${PROXY_HOST} ${PROXY_PORT} ${PROXY_USERNAME} ${PROXY_PASSWORD}
        deny * * * * *
      MAX_CONNECTIONS: 1024
      PRIMARY_RESOLVER: ${DOCKER_INTERNAL_DNS:-}
      PROXY_PORT: 3128
      SECONDARY_RESOLVER: ${DOCKER_INTERNAL_DNS:-}
      SOCKS_PORT: 1080
      TZ: America/Sao_Paulo
    expose:
      - 3128
      - 1080
    networks:
      - media-network
      - infra-network
    restart: unless-stopped

networks:
  media-network:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: "${MEDIA_SUBNET_CIDR:-172.16.0.0/24}"
          gateway: "${MEDIA_SUBNET_GATEWAY:-172.16.0.254}"
  proxy-network:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: "${PROXY_SUBNET_CIDR:-172.16.1.0/24}"
          gateway: "${PROXY_SUBNET_GATEWAY:-172.16.1.254}"
  infra-network:
    driver: bridge
    ipam:
      config:
        - subnet: "${INFRA_SUBNET_CIDR:-172.16.2.0/24}"
          gateway: "${INFRA_SUBNET_GATEWAY:-172.16.2.254}"

volumes:
  downloads_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOWNLOADS_PATH:-.}
  media_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MEDIA_PATH:-.}
  scripts_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${SCRIPTS_PATH:-.}
  certs_lan_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${CONFIGS_PATH:-.}/ssl/lan
  certs_wan_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${CONFIGS_PATH:-.}/ssl/wan
