name: plex
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    hostname: plex.local
    volumes:
      - ../configs/plex:/config
      - ../media:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    ports:
      - 32400:32400
    networks:
      - plex
    restart: unless-stopped

  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    hostname: emby.local
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ../configs/emby:/config
      - ../media:/media
    ports:
      - 8096:8096
    networks:
      - plex
    restart: unless-stopped

  sonarr:
    image: sonarr-mkvtoolnix
    container_name: sonarr
    hostname: sonarr.local
    volumes:
      - ../configs/sonarr:/config
      - ../scripts:/opt/scripts
      - ../media:/media
      - /Users/valeria/Downloads/Torrent:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    ports:
      - 8989:8989
    networks:
      - plex
    restart: unless-stopped

  radarr:
    image: radarr-mkvtoolnix
    container_name: radarr
    hostname: radarr.local
    volumes:
      - ../configs/radarr:/config
      - ../scripts:/opt/scripts
      - ../media:/media
      - /Users/valeria/Downloads/Torrent:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    ports:
      - 7878:7878
    networks:
      - plex
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr.local
    volumes:
      - ../configs/prowlarr:/config
      - ../media/:/media/
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    ports:
      - 9696:9696
    networks:
      - plex
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    hostname: jackett.local
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - AUTO_UPDATE=true
      # - RUN_OPTS=
    volumes:
      - ../configs/jackett:/config
      - /Users/valeria/Downloads/Torrent:/downloads
    ports:
      - 9117:9117
    networks:
      - plex
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    hostname: flaresolverr.local
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - TZ=America/Sao_Paulo
    ports:
      - 8191:8191
    networks:
      - plex
    restart: unless-stopped

  profilarr:
    image: santiagosayshey/profilarr:latest
    container_name: profilarr
    hostname: profilarr.local
    volumes:
      - ../configs/profilarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    ports:
      - 6868:6868
    networks:
      - plex
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    hostname: nginx.local
    volumes:
      - ../configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../configs/nginx/proxy_common.conf:/etc/nginx/proxy_common.conf:ro
      - ../configs/ssl/local/localhost.crt:/config/ssl.lan.crt:ro
      - ../configs/ssl/local/localhost.key:/config/ssl.lan.key:ro
      - ../configs/ssl/wan/apedamo.duckdns.org.crt:/config/ssl.wan.crt:ro
      - ../configs/ssl/wan/apedamo.duckdns.org.key:/config/ssl.wan.key:ro
    depends_on:
      - emby
      - jackett
      - plex
      - profilarr
      - prowlarr
      - radarr
      - sonarr
    ports:
      - 80:80
      - 443:443
    networks:
      - plex
    restart: unless-stopped

networks:
  plex:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/24"
          gateway: "172.16.0.254"
