name: media

services:
  # Infrastructure Services
  caddy:
    image: caddy:latest
    container_name: caddy
    hostname: caddy
    environment:
      TZ: America/Sao_Paulo
    ports:
      - 80:80
      - 443:443
      - 443:443/udp # HTTP/3 (QUIC)
    volumes:
      - ${CONFIGS_PATH}/caddy/Caddyfile:/etc/caddy/Caddyfile:ro,cached
      - ${CERTS_PATH}/lan:/certs/lan:ro,cached
      - ${CERTS_PATH}/wan:/certs/wan:ro,cached
      - ${CERTS_PATH}/ca/ca.crt:/certs/ca/ca.crt:ro,cached
    networks:
      media:
        ipv4_address: 172.16.0.1
    mem_limit: 256m
    restart: unless-stopped

  # dns:
  #   image: coredns/coredns:latest
  #   container_name: dns
  #   hostname: dns
  #   environment:
  #     TZ: America/Sao_Paulo
  #     DOCKER_HOST_IP: ${DOCKER_HOST_IP}
  #     PUBLIC_DNS_IP: ${PUBLIC_DNS_IP}
  #   ports:
  #     - 53:53
  #     - 53:53/udp
  #   volumes:
  #     - ${CONFIGS_PATH}/coredns/Corefile:/Corefile
  #     - ${CONFIGS_PATH}/coredns/configs:/etc/coredns
  #   cap_add:
  #     - NET_BIND_SERVICE
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:53535/health"]
  #     interval: 30s
  #     timeout: 5s
  #     retries: 3
  #   mem_limit: 256m
  #   restart: unless-stopped

  dns:
    image: internetsystemsconsortium/bind9:9.18
    container_name: dns
    hostname: dns
    platform: linux/amd64
    volumes:
      - ${CONFIGS_PATH}/bind/config:/etc/bind
      - ${CONFIGS_PATH}/bind/log:/var/log
    ports:
      - 53:53/udp
      - 53:53
    cap_add:
      - NET_BIND_SERVICE
    mem_limit: 512m
    restart: unless-stopped

  3proxy:
    image: ghcr.io/tarampampam/3proxy
    container_name: 3proxy
    hostname: proxy
    volumes:
      - ${CONFIGS_PATH}/3proxy/3proxy.cfg:/etc/3proxy/3proxy.cfg
    environment:
      EXTRA_CONFIG: |
        auth iponly
        allow * * *.media.lan * *
        allow * * *.plex.direct * *
        allow * * 172.16.0.0/24 * *
        allow * * 172.16.1.0/24 * *
        allow * * 172.16.2.0/24 * *
        parent 1000 connect+ 0.0.0.0 0
        allow *
        parent 1000 ${PROXY_TYPE} ${PROXY_HOST} ${PROXY_PORT} ${PROXY_USERNAME} ${PROXY_PASSWORD}
        deny * * * * *
      MAX_CONNECTIONS: 1024
      PRIMARY_RESOLVER: ${DOCKER_INTERNAL_DNS}
      PROXY_PORT: 3128
      SECONDARY_RESOLVER: ${DOCKER_INTERNAL_DNS}
      SOCKS_PORT: 1080
      TZ: America/Sao_Paulo
    expose:
      - 3128
      - 1080
    networks:
      - proxy
    mem_limit: 256m
    restart: unless-stopped

  # Public Media Services
  emby:
    image: emby/embyserver_arm64v8:latest
    container_name: emby
    hostname: emby
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Sao_Paulo
    volumes:
      - ${CONFIGS_PATH}/emby:/config:cached
      - ${MEDIA_PATH}:/media:cached
    ports:
      - 8096:8096
    networks:
      media:
        ipv4_address: 172.16.0.11
    restart: unless-stopped
    mem_limit: 2g

  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    hostname: plex
    volumes:
      - ${CONFIGS_PATH}/plex:/config:cached
      - ${MEDIA_PATH}:/media:cached
    environment:
      ADVERTISE_IP: ${PLEX_ADVERTISE_IP}
      PGID: 1000
      PLEX_CLAIM: ${PLEX_CLAIM}
      PUID: 1000
      TZ: America/Sao_Paulo
      VERSION: docker
    ports:
      - 32400:32400/tcp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 8324:8324/tcp
    networks:
      media:
        ipv4_address: 172.16.0.19
    restart: unless-stopped
    mem_limit: 2g

  # Private Media Services
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Sao_Paulo
    volumes:
      - ${CONFIGS_PATH}/bazarr:/config:cached
      - ${MEDIA_PATH}:/media:delegated
    expose:
      - 6767
    networks:
      media:
        ipv4_address: 172.16.0.12
        priority: 1
        gw_priority: 1
      proxy:
    restart: unless-stopped
    mem_limit: 1g

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    hostname: jackett
    environment:
      AUTO_UPDATE: true
      PGID: 1000
      PUID: 1000
      TZ: America/Sao_Paulo
    volumes:
      - ${CONFIGS_PATH}/jackett:/config:cached
    expose:
      - 9117
    networks:
      media:
        ipv4_address: 172.16.0.13
      proxy:
    restart: unless-stopped
    mem_limit: 512m

  profilarr:
    image: santiagosayshey/profilarr:latest
    container_name: profilarr
    hostname: profilarr
    volumes:
      - ${CONFIGS_PATH}/profilarr:/config:rw
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Sao_Paulo
    expose:
      - 6868
    networks:
      media:
        ipv4_address: 172.16.0.14
    restart: unless-stopped
    mem_limit: 256m

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    volumes:
      - ${CONFIGS_PATH}/prowlarr:/config:cached
      - ${MEDIA_PATH}:/media:delegated
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Sao_Paulo
    expose:
      - 9696
    networks:
      media:
        ipv4_address: 172.16.0.15
      proxy:
    restart: unless-stopped
    mem_limit: 512m

  lidarr:
    image: ghcr.io/hotio/lidarr:pr-plugins
    container_name: lidarr
    hostname: lidarr
    volumes:
      - ${CONFIGS_PATH}/lidarr:/config:cached
      - ${DOWNLOADS_PATH}:/downloads:delegated
      - ${MEDIA_PATH}:/media:delegated
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Sao_Paulo
    expose:
      - 8686
    networks:
      media:
        ipv4_address: 172.16.0.18
    restart: unless-stopped
    mem_limit: 512m

  radarr:
    build:
      context: ${DOCKER_BUILD_CONTEXT}
      dockerfile: ${RADARR_DOCKERFILE_PATH}
      tags:
        - ${RADARR_IMAGE_NAME}
    container_name: radarr
    hostname: radarr
    volumes:
      - ${CONFIGS_PATH}/radarr:/config:cached
      - ${DOWNLOADS_PATH}:/downloads:delegated
      - ${MEDIA_PATH}:/media:delegated
      - ${SCRIPTS_PATH}:/opt/scripts:ro
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Sao_Paulo
    expose:
      - 7878
    networks:
      media:
        ipv4_address: 172.16.0.16
    restart: unless-stopped
    mem_limit: 1g

  sonarr:
    build:
      context: ${DOCKER_BUILD_CONTEXT}
      dockerfile: ${SONARR_DOCKERFILE_PATH}
      tags:
        - ${SONARR_IMAGE_NAME}
    container_name: sonarr
    hostname: sonarr
    volumes:
      - ${CONFIGS_PATH}/sonarr:/config:cached
      - ${DOWNLOADS_PATH}:/downloads:delegated
      - ${MEDIA_PATH}:/media:delegated
      - ${SCRIPTS_PATH}:/opt/scripts:ro
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Sao_Paulo
    expose:
      - 8989
    networks:
      media:
        ipv4_address: 172.16.0.17
    restart: unless-stopped
    mem_limit: 1g

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    hostname: flaresolverr
    environment:
      CAPTCHA_SOLVER: none
      LOG_HTML: false
      LOG_LEVEL: info
      TZ: America/Sao_Paulo
    expose:
      - 8191
    networks:
      media:
        ipv4_address: 172.16.0.21
      proxy:
    restart: unless-stopped
    mem_limit: 512m
    memswap_limit: 1g

  # Download Services
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    environment:
      PGID: 1000
      PUID: 1000
      TORRENTING_PORT: 53471
      TZ: America/Sao_Paulo
      WEBUI_PORT: 8081
    volumes:
      - ${CONFIGS_PATH}/qbittorrent:/config:cached
      - ${DOWNLOADS_PATH}:/downloads:delegated
    expose:
      - 8081
    ports:
      - 53471:53471
      - 53471:53471/udp
    networks:
      media:
        ipv4_address: 172.16.0.20
    mem_limit: 512m
    restart: unless-stopped

  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    hostname: slskd
    environment:
      SLSKD_REMOTE_CONFIGURATION: true
      SLSKD_SHARED_DIR: /music
      TZ: America/Sao_Paulo
    volumes:
      - ${CONFIGS_PATH}/slskd:/app:cached
      - ${DOWNLOADS_PATH}:/app/downloads:delegated
      - ${MEDIA_PATH}/Music:/music:delegated
    expose:
      - 5030
    networks:
      media:
        ipv4_address: 172.16.0.22
    mem_limit: 512m
    restart: unless-stopped

networks:
  media:
    name: media
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1492
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/24"
          gateway: "172.16.0.254"
  proxy:
    name: proxy
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1492
    ipam:
      config:
        - subnet: "172.16.1.0/24"
          gateway: "172.16.1.254"

