apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-deployment
  namespace: infra
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: adguard
  template:
    metadata:
      labels:
        app: adguard
    spec:
      containers:
        - name: adguard-home
          image: adguard/adguardhome:latest
          ports:
            - containerPort: 3000
              name: http-initial
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 853
              name: dot-tcp
              protocol: TCP
            - containerPort: 853
              name: dot-udp
              protocol: UDP
          volumeMounts:
            - name: configs
              subPath: adguard
              mountPath: /opt/adguardhome/work
            - name: configs
              subPath: adguard-conf
              mountPath: /opt/adguardhome/conf
            - name: certs
              mountPath: /opt/adguardhome/certs
              readOnly: true
      volumes:
        - name: configs
          persistentVolumeClaim:
            claimName: configs-pvc
        - name: certs
          secret:
            secretName: wan-wildcard-tls
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-service
  namespace: infra
spec:
  selector:
    app: adguard
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http-initial
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 53
      targetPort: 53
      nodePort: 53
      name: dns-tcp
    - protocol: UDP
      port: 53
      targetPort: 53
      nodePort: 53
      name: dns-udp
    - protocol: TCP
      port: 853
      targetPort: 853
      nodePort: 853
      name: dot-tcp
    - protocol: UDP
      port: 853
      targetPort: 853
      nodePort: 853
      name: dot-udp
  type: LoadBalancer
  externalTrafficPolicy: Local
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/target: "${DOCKER_HOST_IP}"
  name: adguard-lan
  namespace: infra
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`adguard.infra.lan`) || Host(`adguard.infra.${WAN_HOSTNAME}`) || Host(`adguard-service`)
      kind: Rule
      services:
        - name: adguard-service
          port: 80
    - match: (Host(`adguard-setup.infra.lan`) || Host(`adguard-setup.infra.${WAN_HOSTNAME}`))
      kind: Rule
      services:
        - name: adguard-service
          port: 3000
  tls:
    secretName: media-lan-tls
