apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest
  namespace: infra
  labels:
    app: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      containers:
        - name: speedtest
          image: linuxserver/librespeed
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest
  namespace: infra
spec:
  selector:
    app: speedtest
  ports:
    - name: http
      port: 3000
      targetPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: speedtest-lan
  namespace: infra
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`speedtest.infra.lan`) || Host(`speedtest.infra.${WAN_HOSTNAME}`) || Host(`speedtest-service`)
      kind: Rule
      priority: 100
      services:
        - name: speedtest
          port: 3000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: speedtest-wan
  namespace: infra
spec:
  entryPoints:
    - web-wan
    - websecure-wan
  routes:
    - match: Host(`speedtest.infra.${WAN_HOSTNAME}`)
      kind: Rule
      services:
        - name: speedtest
          port: 3000
