[Interface]
Address = ${WG_PEER1_IP}
PrivateKey = ${WG_PEER1_PRIVATE_KEY}
ListenPort = ${WG_SERVER_PORT}
DNS = ${WG_SERVER_IP}
MTU = ${WG_MTU}

[Peer]
PublicKey = ${WG_SERVER_PUBLIC_KEY}
PresharedKey = ${WG_PEER1_PRESHARED_KEY}
Endpoint = ${WAN_HOST}:${WG_SERVER_PORT}
AllowedIPs = ${WG_SUBNET}, ${DOCKER_HOST_SUBNET}
