[Interface]
Address = 10.13.13.3
PrivateKey = ${WG_PEER2_PRIVATE_KEY}
ListenPort = 51820
DNS = 10.13.13.1
MTU = 1280

[Peer]
PublicKey = ${WG_SERVER_PUBLIC_KEY}
PresharedKey = ${WG_PEER2_PRESHARED_KEY}
Endpoint = apedamo.duckdns.org:51820
AllowedIPs = 10.13.13.0/24, 192.168.2.0/24
