[Interface]
Address = 10.13.13.1
PrivateKey = ${WG_SERVER_PRIVATE_KEY}
ListenPort = 51820
PostUp = /etc/wireguard/postup.sh %i
PostDown = /etc/wireguard/postdown.sh %i
MTU = 1400

[Peer]
# peer_XiaomiMI9
PublicKey = ${WG_PEER1_PUBLIC_KEY}
PresharedKey = ${WG_PEER1_PRESHARED_KEY}
AllowedIPs = 10.13.13.2/32
PersistentKeepalive = 25

[Peer]
# peer_PocoM4
PublicKey = ${WG_PEER2_PUBLIC_KEY}
PresharedKey = ${WG_PEER2_PRESHARED_KEY}
AllowedIPs = 10.13.13.3/32
PersistentKeepalive = 25
