[Interface]
Address = ${WG_SERVER_IP}
PrivateKey = ${WG_SERVER_PRIVATE_KEY}
ListenPort = ${WG_SERVER_PORT}
PostUp = /etc/wireguard/postup.sh %i
PostDown = /etc/wireguard/postdown.sh %i
MTU = ${WG_MTU}

[Peer]
PublicKey = ${WG_PEER1_PUBLIC_KEY}
PresharedKey = ${WG_PEER1_PRESHARED_KEY}
AllowedIPs = ${WG_PEER1_IP}/32
PersistentKeepalive = 25

[Peer]
PublicKey = ${WG_PEER2_PUBLIC_KEY}
PresharedKey = ${WG_PEER2_PRESHARED_KEY}
AllowedIPs = ${WG_PEER2_IP}/32
PersistentKeepalive = 25
